// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WalkThePark.Models;

namespace Parks.Migrations
{
    [DbContext(typeof(WalkTheParkContext))]
    [Migration("20200821211613_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WalkThePark.Models.NationalPark", b =>
                {
                    b.Property<int>("NationalParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessPrice");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("State")
                        .IsRequired();

                    b.HasKey("NationalParkId");

                    b.ToTable("NationalParks");

                    b.HasData(
                        new
                        {
                            NationalParkId = 1,
                            AccessPrice = 30,
                            Name = "Crater_Lake_National_Park",
                            State = "Oregon"
                        },
                        new
                        {
                            NationalParkId = 2,
                            AccessPrice = 10,
                            Name = "Oregon_Caves_National_Park",
                            State = "Oregon"
                        },
                        new
                        {
                            NationalParkId = 3,
                            AccessPrice = 10,
                            Name = "Fort_Vancouver_National_Park",
                            State = "Washington"
                        },
                        new
                        {
                            NationalParkId = 4,
                            AccessPrice = 0,
                            Name = "San_Juan_National_Park",
                            State = "Washington"
                        },
                        new
                        {
                            NationalParkId = 5,
                            AccessPrice = 0,
                            Name = "Point_Reyes_National_Park",
                            State = "California"
                        },
                        new
                        {
                            NationalParkId = 6,
                            AccessPrice = 0,
                            Name = "Golden_Gate_National_Park",
                            State = "California"
                        });
                });

            modelBuilder.Entity("WalkThePark.Models.StatePark", b =>
                {
                    b.Property<int>("StateParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("County");

                    b.Property<string>("Name");

                    b.Property<string>("State");

                    b.HasKey("StateParkId");

                    b.ToTable("StateParks");

                    b.HasData(
                        new
                        {
                            StateParkId = 1,
                            County = "Coos",
                            Name = "Bandon_State_Natural_Area",
                            State = "Oregon"
                        },
                        new
                        {
                            StateParkId = 2,
                            County = "Linn",
                            Name = "Cascadia_State_Park",
                            State = "Oregon"
                        },
                        new
                        {
                            StateParkId = 3,
                            County = "Island",
                            Name = "Fort_Ebey_State_Park",
                            State = "Washington"
                        },
                        new
                        {
                            StateParkId = 4,
                            County = "Kittitas",
                            Name = "Ginkgo_Petrified_Forest",
                            State = "Washington"
                        },
                        new
                        {
                            StateParkId = 5,
                            County = "El_Dorado",
                            Name = "Emerald_Bay_State_Park",
                            State = "California"
                        },
                        new
                        {
                            StateParkId = 6,
                            County = "Humboldt",
                            Name = "Grizzly_Creek_Redwoods",
                            State = "California"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
